services:
  - type: web
    plan: free
    name: forwardwithfilter
    env: docker
    #buildCommand: pip install -U -r requirements.txt
    #startCommand: gunicorn app:app & python3 -m Zaid
    repo: https://github.com/assc0d3r/ART-Auto-ForwardBot      
    branch: main
    envVars:
      - key:  API_ID 
        sync: false
      - key: BOT_TOKEN 
        sync: false
      - key: OWNER_ID 
        sync: false
      - key: BOT_SESSION
        sync: false
      - key: API_HASH
        sync: false
      - key: CAPTION
        sync: false 
      - key: FILTER_TYPE
        sync: false 
      - key: SESSION
        sync: false 
    autoDeploy: false
